from PyQt5 import QtCore, QtGui, QtWidgets
from student_dataentry import Ui_MainWindow3
from Liststudents import Ui_MainWindow9

class Ui_MainWindow4(object):

    def student_entry(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow3()
        self.ui.setupUi(self.window)
        self.window.show()

    def student_show(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow9()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, MainWindow4):
        MainWindow4.setObjectName("MainWindow4")
        MainWindow4.resize(672, 460)
        MainWindow4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.489, x2:0.971591, y2:0.494, stop:0.0738636 rgba(0, 117, 232, 255), stop:1 rgba(255, 255, 255, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow4)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(96, 10, 491, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.b1 = QtWidgets.QPushButton(self.centralwidget)
        self.b1.setGeometry(QtCore.QRect(80, 140, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.b1.setFont(font)
        self.b1.setObjectName("b1")
        self.b4 = QtWidgets.QPushButton(self.centralwidget)
        self.b4.setGeometry(QtCore.QRect(420, 140, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setItalic(False)
        font.setUnderline(True)
        self.b4.setFont(font)
        self.b4.setObjectName("b4")
        self.b2 = QtWidgets.QPushButton(self.centralwidget)
        self.b2.setGeometry(QtCore.QRect(80, 240, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.b2.setFont(font)
        self.b2.setObjectName("b2")
        self.b2.clicked.connect(self.student_show)
        self.b6 = QtWidgets.QPushButton(self.centralwidget)
        self.b6.setGeometry(QtCore.QRect(420, 340, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.b6.setFont(font)
        self.b6.setObjectName("b6")
        self.b5 = QtWidgets.QPushButton(self.centralwidget)
        self.b5.setGeometry(QtCore.QRect(420, 240, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.b5.setFont(font)
        self.b5.setObjectName("b5")
        self.b3 = QtWidgets.QPushButton(self.centralwidget)
        self.b3.setGeometry(QtCore.QRect(80, 340, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.b3.setFont(font)
        self.b3.setObjectName("b3")
        MainWindow4.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow4)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 672, 21))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow4.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow4)
        self.statusbar.setObjectName("statusbar")
        MainWindow4.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow4)
        self.actionAbout.setObjectName("actionAbout")
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuHelp.menuAction())
        self.b1.clicked.connect(self.student_entry)

        self.retranslateUi(MainWindow4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow4)

    def retranslateUi(self, MainWindow4):
        _translate = QtCore.QCoreApplication.translate
        MainWindow4.setWindowTitle(_translate("MainWindow4", "Administrator Options"))
        self.label.setText(_translate("MainWindow4", "Admin Options"))
        self.b1.setStatusTip(_translate("MainWindow4", "Add new Students."))
        self.b1.setText(_translate("MainWindow4", "Add Students"))
        self.b4.setStatusTip(_translate("MainWindow4", "Add new staff members."))
        self.b4.setText(_translate("MainWindow4", "Add Staff"))
        self.b2.setStatusTip(_translate("MainWindow4", "View student Database."))
        self.b2.setText(_translate("MainWindow4", "View Student"))
        self.b6.setStatusTip(_translate("MainWindow4", "View student complaints against management/staff/teaching problems."))
        self.b6.setText(_translate("MainWindow4", "View Student Complaints"))
        self.b5.setStatusTip(_translate("MainWindow4", "View staff Database."))
        self.b5.setText(_translate("MainWindow4", "View Staff"))
        self.b3.setStatusTip(_translate("MainWindow4", "Add new timetable for students."))
        self.b3.setText(_translate("MainWindow4", "Add Timetable"))
        self.menuHelp.setTitle(_translate("MainWindow4", "Help"))
        self.actionAbout.setText(_translate("MainWindow4", "About"))
        self.actionAbout.setStatusTip(_translate("MainWindow4", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow4 = QtWidgets.QMainWindow()
    ui = Ui_MainWindow4()
    ui.setupUi(MainWindow4)
    MainWindow4.show()
    sys.exit(app.exec_())

