from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3


class Ui_MainWindow7(object):
        
    def get_hw(self):
        div = str(self.divbox.currentText())
        conn = sqlite3.connect("Databases\HW_"+div+".db")
        c = conn.cursor()
        c.execute("CREATE TABLE IF NOT EXISTS hw_data( Subject TEXT, Due_Date TEXT, hw_statement TEXT)")
        s = str(self.sub.currentText())
        var = self.duedate.date() 
        due = str(var.toPyDate())
        hw = str(self.statement.toPlainText())
        c.execute("INSERT INTO hw_data (Subject, Due_Date, hw_statement) VALUES (?, ?, ?)",(s, due, hw))
        #c.execute("INSERT INTO student_data ( name , Div , GR_no , Gender , Phn_no , Branch , DOB , crnt_CGPA , Address , Ad_no ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",( name , div , GR , gender , phone , branch , dob , CGPA , Address , Aadhar ))
        conn.commit()
        self.statement.setText("")
        self.sub.setCurrentIndex(0)
        self.divbox.setCurrentIndex(0)
        c.close()
        conn.close()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(703, 427)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.489, x2:0.971591, y2:0.494, stop:0.0738636 rgba(0, 170, 255, 255), stop:1 rgba(255, 255, 255, 255))\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 701, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setToolTipDuration(-18)
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 60, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 120, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(60, 180, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(60, 240, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.assign_button = QtWidgets.QPushButton(self.centralwidget)
        self.assign_button.setGeometry(QtCore.QRect(240, 310, 201, 41))
        self.assign_button.setObjectName("assign_button")
        self.assign_button.clicked.connect(self.get_hw)
        self.divbox = QtWidgets.QComboBox(self.centralwidget)
        self.divbox.setGeometry(QtCore.QRect(350, 180, 281, 31))
        self.divbox.setObjectName("divbox")
        self.divbox.addItem("")
        self.divbox.addItem("")
        self.divbox.addItem("")
        self.divbox.addItem("")
        self.divbox.addItem("")
        self.divbox.addItem("")
        self.divbox.addItem("")
        self.divbox.addItem("")
        self.divbox.addItem("")
        self.divbox.addItem("")
        self.divbox.addItem("")
        self.divbox.addItem("")
        self.divbox.addItem("")
        self.divbox.addItem("")
        self.divbox.addItem("")
        self.divbox.addItem("")
        self.divbox.addItem("")
        self.divbox.addItem("")
        self.divbox.addItem("")
        self.divbox.addItem("")
        self.divbox.addItem("")
        self.statement = QtWidgets.QTextEdit(self.centralwidget)
        self.statement.setGeometry(QtCore.QRect(350, 240, 281, 51))
        self.statement.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.statement.setObjectName("statement")
        self.duedate = QtWidgets.QDateEdit(self.centralwidget)
        self.duedate.setGeometry(QtCore.QRect(350, 120, 281, 31))
        self.duedate.setObjectName("duedate")
        self.sub = QtWidgets.QComboBox(self.centralwidget)
        self.sub.setGeometry(QtCore.QRect(350, 60, 281, 31))
        self.sub.setObjectName("sub")
        self.sub.addItem("")
        self.sub.addItem("")
        self.sub.addItem("")
        self.sub.addItem("")
        self.sub.addItem("")
        self.sub.addItem("")
        self.sub.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 703, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionBack = QtWidgets.QAction(MainWindow)
        self.actionBack.setObjectName("actionBack")
        self.menuMenu.addAction(self.actionBack)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Assign Home Work"))
        self.label.setText(_translate("MainWindow", "Assign Home Work"))
        self.label_2.setText(_translate("MainWindow", "Subject:"))
        self.label_5.setText(_translate("MainWindow", "Due Date(mm,dd,yyyy):"))
        self.label_8.setText(_translate("MainWindow", "Division:"))
        self.label_11.setText(_translate("MainWindow", "Home-Work Statement:"))
        self.assign_button.setText(_translate("MainWindow", "Assign HW"))
        self.divbox.setStatusTip(_translate("MainWindow", "Select division."))
        self.divbox.setItemText(0, _translate("MainWindow", "*Select Division*"))
        self.divbox.setItemText(1, _translate("MainWindow", "A"))
        self.divbox.setItemText(2, _translate("MainWindow", "B"))
        self.divbox.setItemText(3, _translate("MainWindow", "C"))
        self.divbox.setItemText(4, _translate("MainWindow", "D"))
        self.divbox.setItemText(5, _translate("MainWindow", "E"))
        self.divbox.setItemText(6, _translate("MainWindow", "F"))
        self.divbox.setItemText(7, _translate("MainWindow", "G"))
        self.divbox.setItemText(8, _translate("MainWindow", "H"))
        self.divbox.setItemText(9, _translate("MainWindow", "I"))
        self.divbox.setItemText(10, _translate("MainWindow", "J"))
        self.divbox.setItemText(11, _translate("MainWindow", "K"))
        self.divbox.setItemText(12, _translate("MainWindow", "L"))
        self.divbox.setItemText(13, _translate("MainWindow", "M"))
        self.divbox.setItemText(14, _translate("MainWindow", "N"))
        self.divbox.setItemText(15, _translate("MainWindow", "O"))
        self.divbox.setItemText(16, _translate("MainWindow", "P"))
        self.divbox.setItemText(17, _translate("MainWindow", "Q"))
        self.divbox.setItemText(18, _translate("MainWindow", "R"))
        self.divbox.setItemText(19, _translate("MainWindow", "S"))
        self.divbox.setItemText(20, _translate("MainWindow", "T"))
        self.statement.setStatusTip(_translate("MainWindow", "Enter Home Work Statement.."))
        self.duedate.setStatusTip(_translate("MainWindow", "Select Due Date"))
        self.sub.setStatusTip(_translate("MainWindow", "Select Suubject."))
        self.sub.setItemText(0, _translate("MainWindow", "*Select Subject*"))
        self.sub.setItemText(1, _translate("MainWindow", "Mathematics"))
        self.sub.setItemText(2, _translate("MainWindow", "Python Programming"))
        self.sub.setItemText(3, _translate("MainWindow", "Mechatronics"))
        self.sub.setItemText(4, _translate("MainWindow", "Quantitative Analysis"))
        self.sub.setItemText(5, _translate("MainWindow", "SDP"))
        self.sub.setItemText(6, _translate("MainWindow", "ACP"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionBack.setText(_translate("MainWindow", "Help"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow7 = QtWidgets.QMainWindow()
    ui = Ui_MainWindow7()
    ui.setupUi(MainWindow7)
    MainWindow7.show()
    sys.exit(app.exec_())
