from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3

class Ui_MainWindow9(object):
    def _load(self):
        conn = sqlite3.connect("Databases\Student.db")
        c = conn.cursor()
        q = "SELECT * FROM student_data"
        res = c.execute(q)
        for rno, rdta in enumerate(res):
            self.tableWidget.insertRow(rno)
            for colno, coldata in enumerate(rdta):
                self.tableWidget.setItem(rno, colno, QtWidgets.QTableWidgetItem(str(coldata)))
        conn.close()        

    def _sort(self):
        self.tableWidget.clearContents()
        parameter = str(self.comboBox.currentText())
        q = "SELECT * FROM student_data ORDER BY " + parameter
        conn = sqlite3.connect("Databases\Student.db")
        c = conn.cursor()
        res = c.execute(q)
        data = c.fetchall()
        for rno, rdta in enumerate(data):
            self.tableWidget.insertRow(rno)
            for colno, coldata in enumerate(rdta):
                self.tableWidget.setItem(rno, colno, QtWidgets.QTableWidgetItem(str(coldata)))
        conn.close()              

    def _search(self):
        self.tableWidget.clearContents()
        parameter = str(self.comboBox_2.currentText())
        val = str(self.textEdit.toPlainText())
        conn = sqlite3.connect("Databases\Student.db")
        c = conn.cursor()
        q = "SELECT * FROM student_data WHERE "+parameter+" = "+'"'+val+'"'
        res = c.execute(q)
        data = c.fetchall()
        for rno, rdta in enumerate(data):
            self.tableWidget.insertRow(rno)
            for colno, coldata in enumerate(rdta):
                self.tableWidget.setItem(rno, colno, QtWidgets.QTableWidgetItem(str(coldata)))
        conn.close()

    def setupUi(self, MainWindow9):
        MainWindow9.setObjectName("MainWindow9")
        MainWindow9.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow9.resize(1490, 892)
        MainWindow9.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.489, x2:0.971591, y2:0.494, stop:0.0738636 rgba(0, 117, 232, 255), stop:1 rgba(255, 255, 255, 255));")
        MainWindow9.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtWidgets.QWidget(MainWindow9)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-4, 10, 1501, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 260, 1471, 601))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setRowCount(100)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        self.tableWidget.setColumnWidth(0,250)
        self.tableWidget.setColumnWidth(1,110)
        self.tableWidget.setColumnWidth(2,70)
        self.tableWidget.setColumnWidth(3,160)
        self.tableWidget.setColumnWidth(4,90)
        self.tableWidget.setColumnWidth(5,150)
        self.tableWidget.setColumnWidth(6,150)
        self.tableWidget.setColumnWidth(7,90)
        self.tableWidget.setColumnWidth(8,110)
        self.tableWidget.setColumnWidth(9,240)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setItem(0, 0, item)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(190, 90, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(190, 160, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(510, 90, 551, 41))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(510, 160, 171, 41))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(7, "")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(710, 160, 351, 41))
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        self.Load = QtWidgets.QPushButton(self.centralwidget)
        self.Load.setGeometry(QtCore.QRect(80, 90, 80, 111))
        self.Load.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.Load.setToolTipDuration(-2)
        self.Load.setObjectName("load")
        self.Load.clicked.connect(self._load)
        self.Sort = QtWidgets.QPushButton(self.centralwidget)
        self.Sort.setGeometry(QtCore.QRect(1130, 90, 231, 41))
        self.Sort.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.Sort.setToolTipDuration(-2)
        self.Sort.setObjectName("Sort")
        self.Sort.clicked.connect(self._sort)
        self.search = QtWidgets.QPushButton(self.centralwidget)
        self.search.setGeometry(QtCore.QRect(1130, 160, 231, 41))
        self.search.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.search.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.search.setObjectName("Search")
        self.search.clicked.connect(self._search)
        MainWindow9.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow9)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1490, 21))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow9.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow9)
        self.statusbar.setObjectName("statusbar")
        MainWindow9.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow9)
        self.actionAbout.setObjectName("actionAbout")
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow9)
        QtCore.QMetaObject.connectSlotsByName(MainWindow9)

    def retranslateUi(self, MainWindow9):
        _translate = QtCore.QCoreApplication.translate
        MainWindow9.setWindowTitle(_translate("MainWindow9", "Student List"))
        self.label.setText(_translate("MainWindow9", "View Students"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow9", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow9", "GR"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow9", "Div"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow9", "Branch"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow9", "Gender"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow9", "Aadhar Number"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow9", "Ph No."))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow9", "CGPA"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow9", "DOB"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow9", "Address"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("MainWindow9", "Sort By:"))
        self.label_3.setText(_translate("MainWindow9", "Search by:"))
        self.comboBox.setItemText(0, _translate("MainWindow9", "*Select Parameter*"))
        self.comboBox.setItemText(1, _translate("MainWindow9", "Branch"))
        self.comboBox.setItemText(2, _translate("MainWindow9", "GR_no"))
        self.comboBox.setItemText(3, _translate("MainWindow9", "Div"))
        self.comboBox.setItemText(4, _translate("MainWindow9", "name"))
        self.comboBox_2.setItemText(0, _translate("MainWindow9", "*Select Parameter*"))
        self.comboBox_2.setItemText(1, _translate("MainWindow9", "name"))
        self.comboBox_2.setItemText(2, _translate("MainWindow9", "Div"))
        self.comboBox_2.setItemText(3, _translate("MainWindow9", "GR_no"))
        self.comboBox_2.setItemText(4, _translate("MainWindow9", "Phn_no"))
        self.comboBox_2.setItemText(5, _translate("MainWindow9", "Branch"))
        self.comboBox_2.setItemText(6, _translate("MainWindow9", "DOB(yyyy-mm-dd)"))
        self.textEdit.setStatusTip(_translate("MainWindow9", "Enter Value to be  searhed."))
        self.textEdit.setHtml(_translate("MainWindow9", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p></body></html>"))
        self.Sort.setStatusTip(_translate("MainWindow9", "Sorts Database"))
        self.Sort.setText(_translate("MainWindow9", "Sort"))
        self.search.setStatusTip(_translate("MainWindow9", "Searches database"))
        self.search.setText(_translate("MainWindow9", "Search"))
        self.Load.setText(_translate("MainWindow9", "Load\nData"))
        self.Load.setStatusTip(_translate("MainWindow9", "Loads Student Database"))
        self.menuHelp.setTitle(_translate("MainWindow9", "Help"))
        self.actionAbout.setText(_translate("MainWindow9", "About"))
        self.actionAbout.setStatusTip(_translate("MainWindow9", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow9 = QtWidgets.QMainWindow()
    ui = Ui_MainWindow9()
    ui.setupUi(MainWindow9)
    MainWindow9.show()
    sys.exit(app.exec_())