from PyQt5 import QtCore, QtGui, QtWidgets
from admin import Ui_MainWindow1
from staff import Ui_MainWindow2
from Student_optns import Ui_MainWindow6
class Ui_MainWindow(object):

    def admin_event(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow1()
        self.ui.setupUi(self.window)
        self.window.show()
    
    def staff_event(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow2()
        self.ui.setupUi(self.window)
        self.window.show()

    def student_event(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow6()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(718, 401)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../ACP/random/hnet.com-image.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(" background-color:rgb(0, 85, 127) ;")
        MainWindow.setAnimated(True)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.heading_label = QtWidgets.QLabel(self.centralwidget)
        self.heading_label.setGeometry(QtCore.QRect(100, 0, 521, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.heading_label.setFont(font)
        self.heading_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.heading_label.setAutoFillBackground(False)
        self.heading_label.setTextFormat(QtCore.Qt.AutoText)
        self.heading_label.setScaledContents(False)
        self.heading_label.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.heading_label.setWordWrap(False)
        self.heading_label.setObjectName("heading_label")
        self.button1 = QtWidgets.QPushButton(self.centralwidget)
        self.button1.setGeometry(QtCore.QRect(270, 140, 181, 41))
        self.button1.setStyleSheet(" background-color: rgb(170, 170, 255);")
        self.button1.setObjectName("button1")
        self.button1.clicked.connect(self.admin_event)
        self.button2 = QtWidgets.QPushButton(self.centralwidget)
        self.button2.setGeometry(QtCore.QRect(270, 210, 181, 41))
        self.button2.setStyleSheet(" background-color: rgb(0, 170, 255);")
        self.button2.setObjectName("button2")
        self.button2.clicked.connect(self.staff_event)
        self.button3 = QtWidgets.QPushButton(self.centralwidget)
        self.button3.setGeometry(QtCore.QRect(270, 280, 181, 41))
        self.button3.setAutoFillBackground(False)
        self.button3.setStyleSheet(" background-color: rgb(85, 170, 127);")
        self.button3.setCheckable(False)
        self.button3.setObjectName("button3")
        self.button3.clicked.connect(self.student_event)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 718, 21))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.admindocs = QtWidgets.QAction(MainWindow)
        self.admindocs.setObjectName("admindocs")
        self.staffdocs = QtWidgets.QAction(MainWindow)
        self.staffdocs.setObjectName("staffdocs")
        self.studentdocs = QtWidgets.QAction(MainWindow)
        self.studentdocs.setObjectName("studentdocs")
        self.menuHelp.addAction(self.admindocs)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.staffdocs)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.studentdocs)
        self.menuHelp.addSeparator()
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Student Database Management Management"))
        self.heading_label.setText(_translate("MainWindow", "STUDENT DATABASE MANAGEMENT SYSTEM"))
        self.button1.setStatusTip(_translate("MainWindow", "Login as Administrator."))
        self.button1.setText(_translate("MainWindow", "Administrator"))
        self.button2.setStatusTip(_translate("MainWindow", "Login as Staff"))
        self.button2.setText(_translate("MainWindow", "Staff"))
        self.button3.setStatusTip(_translate("MainWindow", "Login as Student."))
        self.button3.setText(_translate("MainWindow", "Student"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.admindocs.setText(_translate("MainWindow", "Admin"))
        self.staffdocs.setText(_translate("MainWindow", "Staff"))
        self.studentdocs.setText(_translate("MainWindow", "Student"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
