from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import sqlite3

conn = sqlite3.connect("Databases\Student.db")
c = conn.cursor()
c.execute("CREATE TABLE IF NOT EXISTS student_data( name TEXT, GR_no TEXT, Div TEXT, Branch TEXT, Gender TEXT, Ad_no TEXT, Phn_no TEXT, crnt_CGPA TEXT, DOB TEXT, Address TEXT)")
            

class Ui_MainWindow3(object):

    def get_std_info(self):
            name = self.name.toPlainText()
            GR = str(self.gr.toPlainText())
            phone = str(self.phno.toPlainText())
            Aadhar = str(self.adno.toPlainText())
            var = self.dateEdit.date() 
            dob = str(var.toPyDate())
            CGPA = str(self.cgpa.toPlainText())
            Address = self.address.toPlainText()
            branch = str(self.branchbox.currentText())
            div = str(self.divbox.currentText())
            gender = str(self.genderbox.currentText())
            c.execute("INSERT INTO student_data ( name , GR_no , Div , Branch , Gender , Ad_no , Phn_no , crnt_CGPA , DOB , Address ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",( name , GR , div , branch , gender , Aadhar , phone , CGPA , dob , Address ))
            self.phno.setText("")
            self.name.setText("")
            self.gr.setText("")
            self.adno.setText("")
            self.cgpa.setText("")
            self.address.setText("")
            self.branchbox.setCurrentIndex(0)
            self.genderbox.setCurrentIndex(0)
            self.divbox.setCurrentIndex(0)
            conn.commit()


    def reset(self):
            self.phno.setText("")
            self.name.setText("")
            self.gr.setText("")
            self.adno.setText("")
            self.cgpa.setText("")
            self.address.setText("")
            self.branchbox.setCurrentIndex(0)
            self.genderbox.setCurrentIndex(0)
            self.divbox.setCurrentIndex(0)    

    def back(self):
            c.close()
            conn.close()
            pass
        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(878, 746)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.489, x2:0.971591, y2:0.494, stop:0.0738636 rgba(85, 170, 127, 255), stop:1 rgba(255, 255, 255, 255))\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 0, 651, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setToolTipDuration(-18)
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 70, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 130, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(170, 250, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(170, 190, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(170, 370, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(170, 430, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(170, 490, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(170, 310, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(170, 550, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(170, 610, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.back_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_button.setGeometry(QtCore.QRect(100, 670, 201, 31))
        self.back_button.setObjectName("back_button")
        self.back_button.clicked.connect(self.back)
        self.add_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_button.setGeometry(QtCore.QRect(350, 670, 201, 31))
        self.add_button.setObjectName("add_button")
        self.add_button.clicked.connect(self.get_std_info)
        self.RefreshButton = QtWidgets.QPushButton(self.centralwidget)
        self.RefreshButton.setGeometry(QtCore.QRect(600, 670, 201, 31))
        self.RefreshButton.setObjectName("RefreshButton")
        self.RefreshButton.clicked.connect(self.reset)
        self.branchbox = QtWidgets.QComboBox(self.centralwidget)
        self.branchbox.setGeometry(QtCore.QRect(460, 430, 281, 31))
        self.branchbox.setObjectName("branchbox")
        self.branchbox.addItem("")
        self.branchbox.addItem("")
        self.branchbox.addItem("")
        self.branchbox.addItem("")
        self.branchbox.addItem("")
        self.branchbox.addItem("")
        self.branchbox.addItem("")
        self.divbox = QtWidgets.QComboBox(self.centralwidget)
        self.divbox.setGeometry(QtCore.QRect(460, 490, 281, 31))
        self.divbox.setObjectName("divbox")
        self.divbox.addItem("")
        self.divbox.addItem("")
        self.divbox.addItem("")
        self.divbox.addItem("")
        self.divbox.addItem("")
        self.divbox.addItem("")
        self.divbox.addItem("")
        self.divbox.addItem("")
        self.divbox.addItem("")
        self.divbox.addItem("")
        self.divbox.addItem("")
        self.divbox.addItem("")
        self.divbox.addItem("")
        self.divbox.addItem("")
        self.divbox.addItem("")
        self.divbox.addItem("")
        self.divbox.addItem("")
        self.divbox.addItem("")
        self.divbox.addItem("")
        self.divbox.addItem("")
        self.divbox.addItem("")
        self.phno = QtWidgets.QTextEdit(self.centralwidget)
        self.phno.setGeometry(QtCore.QRect(460, 370, 281, 31))
        self.phno.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.phno.setObjectName("phno")
        self.adno = QtWidgets.QTextEdit(self.centralwidget)
        self.adno.setGeometry(QtCore.QRect(460, 310, 281, 31))
        self.adno.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.adno.setObjectName("adno")
        self.gr = QtWidgets.QTextEdit(self.centralwidget)
        self.gr.setGeometry(QtCore.QRect(460, 250, 281, 31))
        self.gr.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gr.setObjectName("gr")
        self.cgpa = QtWidgets.QTextEdit(self.centralwidget)
        self.cgpa.setGeometry(QtCore.QRect(460, 550, 281, 31))
        self.cgpa.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cgpa.setObjectName("cgpa")
        self.address = QtWidgets.QTextEdit(self.centralwidget)
        self.address.setGeometry(QtCore.QRect(460, 600, 281, 51))
        self.address.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.address.setObjectName("address")
        self.name = QtWidgets.QTextEdit(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(460, 70, 281, 31))
        self.name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.name.setObjectName("name")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(460, 190, 281, 31))
        self.dateEdit.setObjectName("dateEdit")
        self.genderbox = QtWidgets.QComboBox(self.centralwidget)
        self.genderbox.setGeometry(QtCore.QRect(460, 130, 281, 31))
        self.genderbox.setObjectName("genderbox")
        self.genderbox.addItem("")
        self.genderbox.addItem("")
        self.genderbox.addItem("")
        self.genderbox.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 878, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionBack = QtWidgets.QAction(MainWindow)
        self.actionBack.setObjectName("actionBack")
        self.menuMenu.addAction(self.actionBack)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Student Data Entry"))
        self.label_2.setText(_translate("MainWindow", "Name:"))
        self.label_3.setText(_translate("MainWindow", "Gender:"))
        self.label_4.setText(_translate("MainWindow", "GR Number:"))
        self.label_5.setText(_translate("MainWindow", "Date Of Birth(mm-dd-yyyy):"))
        self.label_6.setText(_translate("MainWindow", "Phone Number:"))
        self.label_7.setText(_translate("MainWindow", "Branch:"))
        self.label_8.setText(_translate("MainWindow", "Division:"))
        self.label_9.setText(_translate("MainWindow", "Aadhar Number:"))
        self.label_10.setText(_translate("MainWindow", "CGPA:"))
        self.label_11.setText(_translate("MainWindow", "Address:"))
        self.back_button.setText(_translate("MainWindow", "Back"))
        self.add_button.setText(_translate("MainWindow", "Add Student"))
        self.RefreshButton.setText(_translate("MainWindow", "Refresh"))
        self.branchbox.setStatusTip(_translate("MainWindow", "Select Branch opted by student."))
        self.branchbox.setItemText(0, _translate("MainWindow", "*Select Branch*"))
        self.branchbox.setItemText(1, _translate("MainWindow", "Mechanical Engineering"))
        self.branchbox.setItemText(2, _translate("MainWindow", "Electrical Engineering"))
        self.branchbox.setItemText(3, _translate("MainWindow", "E&TC Engineering"))
        self.branchbox.setItemText(4, _translate("MainWindow", "Chemical Engineering"))
        self.branchbox.setItemText(5, _translate("MainWindow", "Instrumentation Engineering"))
        self.branchbox.setItemText(6, _translate("MainWindow", "Production Engineering"))
        self.divbox.setStatusTip(_translate("MainWindow", "Select division of Student."))
        self.divbox.setItemText(0, _translate("MainWindow", "*Select Division*"))
        self.divbox.setItemText(1, _translate("MainWindow", "A"))
        self.divbox.setItemText(2, _translate("MainWindow", "B"))
        self.divbox.setItemText(3, _translate("MainWindow", "C"))
        self.divbox.setItemText(4, _translate("MainWindow", "D"))
        self.divbox.setItemText(5, _translate("MainWindow", "E"))
        self.divbox.setItemText(6, _translate("MainWindow", "F"))
        self.divbox.setItemText(7, _translate("MainWindow", "G"))
        self.divbox.setItemText(8, _translate("MainWindow", "H"))
        self.divbox.setItemText(9, _translate("MainWindow", "I"))
        self.divbox.setItemText(10, _translate("MainWindow", "J"))
        self.divbox.setItemText(11, _translate("MainWindow", "K"))
        self.divbox.setItemText(12, _translate("MainWindow", "L"))
        self.divbox.setItemText(13, _translate("MainWindow", "M"))
        self.divbox.setItemText(14, _translate("MainWindow", "N"))
        self.divbox.setItemText(15, _translate("MainWindow", "O"))
        self.divbox.setItemText(16, _translate("MainWindow", "P"))
        self.divbox.setItemText(17, _translate("MainWindow", "Q"))
        self.divbox.setItemText(18, _translate("MainWindow", "R"))
        self.divbox.setItemText(19, _translate("MainWindow", "S"))
        self.divbox.setItemText(20, _translate("MainWindow", "T"))
        self.phno.setStatusTip(_translate("MainWindow", "Enter Phone Number of student."))
        self.phno.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p></body></html>"))
        self.adno.setStatusTip(_translate("MainWindow", "Enter Aadhar Number of student."))
        self.adno.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p></body></html>"))
        self.gr.setStatusTip(_translate("MainWindow", "Enter GR Number of student."))
        self.gr.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p></body></html>"))
        self.cgpa.setStatusTip(_translate("MainWindow", "Enter students CGPA. Enter 0 if new admission"))
        self.cgpa.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p></body></html>"))
        self.address.setStatusTip(_translate("MainWindow", "Enter Permanent residential address of student."))
        self.name.setStatusTip(_translate("MainWindow", "Enter name of student."))
        self.name.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p></body></html>"))
        self.dateEdit.setStatusTip(_translate("MainWindow", "Enter Date Of Birth of student."))
        self.genderbox.setStatusTip(_translate("MainWindow", "Select Gender of student."))
        self.genderbox.setItemText(0, _translate("MainWindow", "*Select Gender*"))
        self.genderbox.setItemText(1, _translate("MainWindow", "Male"))
        self.genderbox.setItemText(2, _translate("MainWindow", "Female"))
        self.genderbox.setItemText(3, _translate("MainWindow", "Other"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionBack.setText(_translate("MainWindow", "Help"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow3 = QtWidgets.QMainWindow()
    ui = Ui_MainWindow3()
    ui.setupUi(MainWindow3)
    MainWindow3.show()
    sys.exit(app.exec_())
